InternetAuction/Models/Lot.cs
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InternetAuction.Models
{
    /// <summary>
    /// Model of lot
    /// </summary>
    [Authorize]
    public class Lot
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Укажите название лота!")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Длина строки должна быть от 3 до 50 символов")]
        public string Name { get; set; }
        [StringLength(1000, MinimumLength = 3, ErrorMessage = "Длина строки должна быть от 3 до 1000 символов")]
        public string Desc { get; set; }
        public string City { get; set; }
        public string UserId { get; set; }
        public string BuyerId { get; set; }
        [Required(ErrorMessage = "Укажите стартовую цену лота!")]
        public int StartValue { get; set; }
        public int CurrentValue { get; set; }
        [Required(ErrorMessage = "Укажите минимальное повышение ставки!")]
        public int MinUpgradeBet { get; set; }
        public string Img { get; set; }
        public DateTime StartDate { get; set; }
        [Required(ErrorMessage = "Укажите дату окончания торгов!")]
        public DateTime FinishDate { get; set; }
    }
}

InternetAuction/Controllers/LotController.cs
using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using InternetAuction.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;

namespace InternetAuction.Controllers
{
    /// <summary>
    /// Controller that contains implementation crud functionality to lot model.
    /// </summary>
    /// <remarks>
    /// Can create, update, delete lots.
    /// </remarks>
    /// <remarks>
    /// Display lot page, user lots pages and implement "pay" functionality.
    /// </remarks>
    [Authorize]
    public class LotController : Controller
    {
        private readonly ApplicationContext _db;
        private readonly UserManager<User> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;

        /// <summary>
        /// Initializes a new instance of the <see cref="LotController"/> class.
        /// </summary>
        /// <param name="db">database context</param>
        /// <param name="userManager"></param>
        /// <param name="webHostEnvironment"></param>
        public LotController(ApplicationContext db, UserManager<User> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _webHostEnvironment = webHostEnvironment;
            _userManager = userManager;
        }

        /// <summary>
        /// Display page with current lot data.
        /// </summary>
        /// <param name="id">Id of current lot</param>
        /// <returns>View with current lot data.</returns>
        public async Task<IActionResult> LotPage(int id)
        {
            var model = await _db.Lots.FirstOrDefaultAsync(i => i.Id == id);
            return View(model);
        }

        /// <summary>
        /// Display all lots of current user
        /// </summary>
        /// <returns>View with all lots of current user.</returns>
        public async Task<IActionResult> UserLots()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var model = _db.Lots.Where(i => i.UserId == currentUser.Id).ToList();
            return View(model);
        }

        /// <summary>
        /// Display all current user bet lots that ready to buy.
        /// </summary>
        /// <returns>View with all current user bet lots that ready to buy.</returns>
        public async Task<IActionResult> LotsToBuy()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var model = _db.Lots.Where(i => i.BuyerId == currentUser.Id).ToList();
            return View(model);
        }
        
        /// <summary>
        /// Method which implement "pay" functionality.
        /// </summary>
        /// <param name="id">Identifier of current lot</param>
        /// <returns>View <see cref="LotsToBuy"/>.</returns>
        [HttpPost]
        public async Task<IActionResult> Pay(int id)
        {
            if (id != 0)
            {
                var lot = await _db.Lots.FirstOrDefaultAsync(i => i.Id == id);
                if (lot != null)
                {
                    _db.Remove(lot);
                    await _db.SaveChangesAsync();
                    return RedirectToAction("LotsToBuy");
                }
            }

            return RedirectToAction("Error", "Home");
        }
        /// <summary>
        /// Image resize and save in wwwroot/images folder
        /// </summary>
        /// <param name="image">Uploaded file</param>
        /// <param name="maxWidth">Max width to compress</param>
        /// <param name="filePath">Determined path to save file</param>
        private static async Task ResizeAndUploadImageAsync(Image image, int maxWidth, string 
            filePath)
        {
            await using var writeStream = new MemoryStream();
            if (image.Width > maxWidth)
            {
                var thumbScaleFactor = maxWidth / image.Width;
                image.Mutate(i => i.Resize(maxWidth, image.Height * 
                                                     thumbScaleFactor));
            }

            await image.SaveAsPngAsync(writeStream);
            IFormFile file = new FormFile(writeStream, 0, writeStream.Length, "name", "fileName");
            await file.CopyToAsync(new FileStream(filePath, FileMode.Create));
        }
        
        /// <summary>
        /// Display page with data form of new lot.
        /// </summary>
        /// <returns>View with data form of new lot.</returns>
        public IActionResult Add()
        {
            return View();
        }

        /// <summary>
        /// Get data from form and create a new Lot in database.
        /// </summary>
        /// <param name="lot">Lot data</param>
        /// <param name="image">Uploaded file</param>
        /// <returns>Home page.</returns>
        [HttpPost]
        public async Task<IActionResult> Add(Lot lot, IFormFile image)
        {
            if (image != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                string uniqueFileName = Guid.NewGuid() + "_" + image.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                await using (var stream = image.OpenReadStream())
                using (var toCompress = await Image.LoadAsync(stream))
                {
                    await ResizeAndUploadImageAsync(toCompress, 300, filePath);
                }
                lot.Img = uniqueFileName;
            }
            lot.CurrentValue = lot.StartValue;
            _db.Lots.Add(lot);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Display page with data of current lot
        /// </summary>
        /// <param name="id">Current lot id</param>
        /// <returns>View with form of current lot data.</returns>
        public async Task<IActionResult> Edit(int id)
        {
            
            if (id != 0)
            {
                var currentDate = Convert.ToDateTime(DateTime.Now.ToString(CultureInfo.CurrentCulture));
                var lot = await _db.Lots.FirstOrDefaultAsync(i => i.Id == id);
                var currentUser = await _userManager.GetUserAsync(User);
                var isInRole = await _userManager.IsInRoleAsync(currentUser, "master") || await _userManager.IsInRoleAsync(currentUser, "admin") || await _userManager.IsInRoleAsync(currentUser, "moderator");
                if (lot != null && (lot.UserId == currentUser.Id || isInRole) && lot.FinishDate > currentDate) return View(lot);
            }

            return RedirectToAction("Error", "Home");
        }

        /// <summary>
        /// Get new data from form and update current lot.
        /// </summary>
        /// <param name="lot">Lot data</param>
        /// <param name="image">Uploaded file</param>
        /// <returns>Home page.</returns>
        [HttpPost]
        public async Task<IActionResult> Edit(Lot lot, IFormFile image)
        {
            if (image != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                string uniqueFileName = Guid.NewGuid().ToString() + "_" + image.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                await using (var stream = image.OpenReadStream())
                using (var toCompress = await Image.LoadAsync(stream))
                {
                    await ResizeAndUploadImageAsync(toCompress, 300, filePath);
                }
                lot.Img = uniqueFileName;
            }
            _db.Lots.Update(lot);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
        /// <summary>
        /// Delete current lot from database.
        /// </summary>
        /// <param name="id">Identifier of current lot</param>
        /// <returns>Home page.</returns>
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (id != 0)
            {
                Lot lot = await _db.Lots.FirstOrDefaultAsync(i => i.Id == id);
                if (lot != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(),"wwwroot\\images\\" + lot.Img);
                    if(System.IO.File.Exists(path))
                    {
                        System.IO.File.Delete(path);
                    }
                    _db.Remove(lot);
                    await _db.SaveChangesAsync();
                    return RedirectToAction("Index", "Home");
                }
            }

            return RedirectToAction("Error", "Home");
        }
        
        /// <summary>
        /// Can save new price for lot from user bet.
        /// </summary>
        /// <param name="id">Current lot identifier</param>
        /// <param name="newBet">New price</param>
        /// <param name="buyerId"></param>
        /// <returns>Lot page <see cref="LotPage"/>.</returns>
        public async Task<IActionResult> UpgradeValue(int id, int newBet, string buyerId)
        {
            if (id == 0 || buyerId == null) return NotFound();
            var lot = await _db.Lots.FirstOrDefaultAsync(i => i.Id  == id);
            if (lot == null) return NotFound();
            lot.CurrentValue = newBet;
            lot.BuyerId = buyerId;
            _db.Update(lot);
            await _db.SaveChangesAsync();
            return RedirectToAction("LotPage", new { id });

        }
    }
}

InternetAuction/Views/Lot/Add.cshtml
@using Microsoft.AspNetCore.Identity
@model InternetAuction.Models.Lot
@inject UserManager<User> _userManager
@inject SignInManager<User> _signInManager

@{
    ViewBag.Title = "Creating lot";
    Layout = "_Layout";
	var currentUser = await _userManager.GetUserAsync(User);
}
<form method="post" asp-controller="Lot" asp-action="Add" enctype="multipart/form-data" name="form">
	<div class="validation" asp-validation-summary="ModelOnly"></div>
	<div class="form-group mb-3">
		<label class="form-label d-flex" for="image">Choose image</label>
		<input accept="image/*" class="form-control mb-3" style="width: 300px" type="file" name="image" id="image" onchange="document.getElementById('preview').src = window.URL.createObjectURL(this.files[0])"/>
		<img class="img-fluid" width="300px" height="300px" src="/images/noimage.png" id="preview" alt="Your image"/>
	</div>
	<div class="form-group mb-3">
		<input style="display: none" asp-for="UserId" value="@currentUser.Id">
		<label for="Name" class="form-label d-flex">Lot name:</label>
		<input style="width: 300px" class="form-control" id="Name" placeholder="Example: 10th century ring" asp-for="Name">
		<span asp-validation-for="Name" class="text-danger"></span>
	</div>
	<div class="form-group mb-3">
		<label for="Desc" class="form-label d-flex">Description:</label>
		<textarea class="form-control" style="width: 500px" id="Desc" asp-for="Desc" placeholder="Your description"></textarea>
		<span asp-validation-for="Desc" class="text-danger"></span>
	</div>
	<div class="form-group mb-3">
		<label for="City" class="form-label d-flex">Your city:</label>
		<select style="width: 220px" id="City" class="form-control select-input placeholder-active active" asp-for="City" required>
			<option value="Kiev">Kyiv</option>
			<option value="Kharkov">Kharkov</option>
			<option value="Odessa">Odessa</option>
			<option value="Lvov">Lvov</option>
			<option value="Donetsk">Donetsk</option>
			<option value="Zaporozhye">Zaporozhye</option>
			<option value="Nikolaev">Nikolaev</option>
			<option value="Sevastopol">Sevastopol</option>
			<option value="Mariupol">Mariupol</option>
			<option value="Lugansk">Lugansk</option>
			<option value="Vinnytsa">Vinnytsa</option>
			<option value="Simferopol">Simferopol</option>
			<option value="Herson">Herson</option>
			<option value="Chernigov">Chernigov</option>
			<option value="Poltava">Poltava</option>
			<option value="Cherkassy">Cherkassy</option>
			<option value="Hmelnitskiy">Hmelnitskiy</option>
			<option value="Chernovtsy">Chernovtsy</option>
			<option value="Zhytomyr">Zhytomyr</option>
			<option value="Sumy">Sumy</option>
			<option value="Rovno">Rovno</option>
			<option value="Ivano-Frankovsk">Ivano-Frankovsk</option>
			<option value="Kropivnytsky">Kropivnytsky</option>
			<option value="Ternopol">Ternopol</option>
			<option value="Kremenchug">Kremenchug</option>
			<option value="Lutsk">Lutsk</option>
			<option value="Kramatorsk">Kramatorsk</option>
			<option value="Melitopol">Melitopol</option>
			<option value="Uzhgorod">Uzhgorod</option>
		</select>
	</div>
	<div class="form-group mb-3">
		<label for="Value" class="form-label d-flex">Start price:</label>
		<input class="form-control" style="width: 100px" id="Value" min="1" max="1000000000" asp-for="StartValue"/>
		<span asp-validation-for="StartValue" class="text-danger"></span>
	</div>
	<div class="form-group mb-3">
		<label for="Upgrade" class="form-label d-flex">Minimum upgrade:</label>
		<input class="form-control" style="width: 100px" min="1" max="1000000000" id="Upgrade" asp-for="MinUpgradeBet"/>
		<span asp-validation-for="MinUpgradeBet" class="text-danger"></span>
	</div>
	<div class="form-group mb-3">
		<input style="display: none;" class="form-control" asp-for="StartDate" value="@DateTime.Now.ToString("yyyy-MM-ddTHH:mm")" date-time-format="">
		<label for="finishDate" class="form-label d-flex">End date:</label>
		<input class="form-control" style="width: 220px" id="finishDate" min="@(DateTime.Now.AddHours(1).ToString("yyyy-MM-ddTHH:mm"))" max="@(DateTime.Now.AddDays(30).ToString("yyyy-MM-ddTHH:mm"))" asp-for="FinishDate">
		<span asp-validation-for="FinishDate" class="text-danger"></span>
	</div>
	<input type="submit" class="btn btn-sm btn-secondary mb-2 mt-3" value="Add" />
</form>
@section Scripts {
	<partial name="_ValidationScriptsPartial"/>
}

InternetAuction/Views/Lot/Edit.cshtml
@model InternetAuction.Models.Lot
@{
    ViewBag.Title = "Lot edit";
    Layout = "_Layout";
}

<h2>Edit and click "Save"</h2>
<form method="post" asp-antiforgery="true" asp-controller="Lot" asp-action="Edit" enctype="multipart/form-data">
	<div class="validation" asp-validation-summary="ModelOnly"></div>
	<div class="form-group mb-3">
		<label class="form-label d-flex" for="image">Choose image</label>
		<input accept="image/*" class="form-control mb-3" style="width: 300px" type="file" name="image" id="image" onchange="document.getElementById('preview').src = window.URL.createObjectURL(this.files[0])"/>
		<img class="img-fluid" width="300px" height="300px" src="@("/images/" + (Model.Img ?? "noimage.png"))" id="preview" alt="Ваша картинка"/>
	</div>
	<div class="form-group mb-3">
		<input style="display: none" asp-for="UserId">
		<input style="display: none" asp-for="BuyerId">
		<input style="display: none" asp-for="CurrentValue">
		<input style="display: none;" class="form-control" asp-for="StartDate" value="@Model.StartDate.ToString("yyyy-MM-ddThh:mm")">
		<input style="display:none;" asp-for="Id">
		<input style="display: none" asp-for="StartValue">
		<label for="Name" class="form-label d-flex">Lot name:</label>
		<input style="width: 300px" class="form-control" id="Name" placeholder="Example: 10th century ring" asp-for="Name">
		<span asp-validation-for="Name" class="text-danger"></span>
	</div>
	<div class="form-group mb-3">
		<label for="Desc" class="form-label d-flex">Description:</label>
		<textarea class="form-control" style="width: 500px" id="Desc" asp-for="Desc" placeholder="Your description"></textarea>
		<span asp-validation-for="Desc" class="text-danger"></span>
	</div>
	<div class="form-group mb-3">
		<label for="City" class="form-label d-flex">Your city:</label>
		<select style="width: 220px" id="City" class="form-control select-input placeholder-active active" asp-for="City" required>
			<option value="Kiev">Kyiv</option>
			<option value="Kharkov">Kharkov</option>
			<option value="Odessa">Odessa</option>
			<option value="Lvov">Lvov</option>
			<option value="Donetsk">Donetsk</option>
			<option value="Zaporozhye">Zaporozhye</option>
			<option value="Nikolaev">Nikolaev</option>
			<option value="Sevastopol">Sevastopol</option>
			<option value="Mariupol">Mariupol</option>
			<option value="Lugansk">Lugansk</option>
			<option value="Vinnytsa">Vinnytsa</option>
			<option value="Simferopol">Simferopol</option>
			<option value="Herson">Herson</option>
			<option value="Chernigov">Chernigov</option>
			<option value="Poltava">Poltava</option>
			<option value="Cherkassy">Cherkassy</option>
			<option value="Hmelnitskiy">Hmelnitskiy</option>
			<option value="Chernovtsy">Chernovtsy</option>
			<option value="Zhytomyr">Zhytomyr</option>
			<option value="Sumy">Sumy</option>
			<option value="Rovno">Rovno</option>
			<option value="Ivano-Frankovsk">Ivano-Frankovsk</option>
			<option value="Kropivnytsky">Kropivnytsky</option>
			<option value="Ternopol">Ternopol</option>
			<option value="Kremenchug">Kremenchug</option>
			<option value="Lutsk">Lutsk</option>
			<option value="Kramatorsk">Kramatorsk</option>
			<option value="Melitopol">Melitopol</option>
			<option value="Uzhgorod">Uzhgorod</option>
		</select>
	</div>
	<div class="form-group mb-3">
		<label for="Upgrade" class="form-label d-flex">Minimum upgrade:</label>
		<input class="form-control" style="width: 100px" id="Upgrade"  min="1" max="1000000000" asp-for="MinUpgradeBet"/>
		<span asp-validation-for="MinUpgradeBet" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label for="finishDate">End date:</label>
		<input style="width: 220px" class="form-control" id="finishDate" min="@(DateTime.Now.AddHours(1).ToString("yyyy-MM-ddTHH:mm"))" max="@(DateTime.Now.AddDays(30).ToString("yyyy-MM-ddTHH:mm"))" asp-for="FinishDate">
		<span asp-validation-for="FinishDate" class="text-danger"></span>
	</div>
	<input type="submit" class="btn btn-sm btn-secondary mb-2 mt-3" value="Save" />
</form>
@section Scripts {
	<partial name="_ValidationScriptsPartial"/>
}

InternetAuction/Views/Lot/LotPage.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Globalization
@model InternetAuction.Models.Lot
@inject UserManager<User> _userManager
@{
    ViewBag.Title = "Lot page";
    Layout = "_Layout";
    var currentUser = await _userManager.GetUserAsync(User);
    var timeNow = Convert.ToDateTime(DateTime.Now.ToString(CultureInfo.CurrentCulture));
}
<h6>End date: @Model.FinishDate.ToString("yyyy-MM-dd HH:mm")</h6>
<img style="width: 300px; height: 300px" src="@("/images/" + (Model.Img ?? "noimage.png"))" class="rounded-float-left" alt="no image"/>
<br/>
<h4>Lot name:</h4>
<p style="font-size: 36px; font-weight: bold">@Model.Name</p>
<br/>
<h4>Description:</h4>
<textarea style="width: 300px" class="form-control" disabled>@Model.Desc</textarea>
<br/>
<h4>Seller's city: @Model.City</h4>
<br/>
<h4>Start price:</h4>
<p class="form-control" style="width: max-content">@Model.StartValue</p>
<br/>
<h4>Current price:</h4>
<p class="form-control" style="width: max-content">@Model.CurrentValue</p>
<br/>
<h4>Minimum upgrade:</h4>
<p class="form-control" style="width: max-content">@Model.MinUpgradeBet</p>
<br/>
@if (Model.FinishDate > timeNow && Model.CurrentValue <= 1000000000)
{
    <form asp-controller="Lot" asp-action="UpgradeValue" asp-route-id="@Model.Id">
        <input required class="form-control" style="width: 169px" name="newBet" type="number" min="@(Model.CurrentValue + Model.MinUpgradeBet)" max="@(Int32.MaxValue - Model.CurrentValue)">
        <input style="display: none" type="text" name="buyerId" value="@currentUser.Id">
        <input type="submit" class="btn btn-sm btn-secondary mb-2 mt-3" value="Make bet">
    </form>
}

InternetAuction/Views/Lot/LotsToBuy.cshtml
@using System.Globalization
@model IEnumerable<InternetAuction.Models.Lot>

@{
    ViewBag.Title = "Lots to pay";
    Layout = "_Layout";
    var timeNow = Convert.ToDateTime(DateTime.Now.ToString(CultureInfo.CurrentCulture));
}
<h2>Your current bets</h2>
<table class="table">
    @foreach (var lot in Model.Where(i => i.FinishDate > timeNow))
    {
        <tr>
            <td>
                <div id="image" class="bg-light">
                        <a asp-controller="Lot" asp-action="LotPage" asp-route-id="@lot.Id"><img style="width: 100px; height: 100px" class="mb-3 mt-3 mr-3 ml-3" src="@("/images/" + (lot.Img ?? "noimage.png"))" alt="no image"></a>
                        <a class="btn btn-light" style="font-size: 24px; font-weight: bold" asp-controller="Lot" asp-action="LotPage" asp-route-id="@lot.Id">
                            <span>@lot.Name</span>
                        </a>
                        <span style="float: right; font-weight: bold; font-size: 24px" class="mr-3 ml-3 md-3 mt-3">$@lot.CurrentValue</span>
                    </div>
            </td>
        </tr>
    }
</table>
<h2>Your lots ready to pay</h2>
<table class="table">
    @foreach (var lot in Model.Where(i => i.FinishDate <= timeNow))
    {
        <tr>
            <td>
                <div id="image" class="bg-light">
                        <a asp-controller="Lot" asp-action="LotPage" asp-route-id="@lot.Id"><img style="width: 100px; height: 100px" class="mb-3 mt-3 mr-3 ml-3" src="@("/images/" + (lot.Img ?? "noimage.png"))" alt="no image"></a>
                        <a class="btn btn-light" style="font-size: 24px; font-weight: bold" asp-controller="Lot" asp-action="LotPage" asp-route-id="@lot.Id">
                            <span>@lot.Name</span>
                        </a>
                        <span style="float: right; font-weight: bold; font-size: 24px" class="mr-3 ml-3 md-3 mt-3">$@lot.CurrentValue</span>
                    </div>
            </td>
            <td>
                <form method="post" asp-action="Pay" asp-controller="Lot" asp-route-id="@lot.Id">
                    <input class="btn btn-sm btn-primary" type="submit" value="Pay" onclick="return confirm('Are you sure to pay for this lot?')"/>
                </form>
            </td>
        </tr>
    }
</table>

InternetAuction/Views/Lot/UserLots.cshtml
@using System.Globalization
@model IEnumerable<InternetAuction.Models.Lot>

@{
    ViewBag.Title = "Ваши лоты";
    Layout = "_Layout";
    var timeNow = Convert.ToDateTime(DateTime.Now.ToString(CultureInfo.CurrentCulture));
}

<h2>All your lots</h2>
<table class="table">
    @foreach (var lot in Model)
    {
        <tr>
            <td>
                <div id="image" class="bg-light">
                    @if (lot.FinishDate > timeNow)
                    {
                        <a asp-controller="Lot" asp-action="Edit" asp-route-id="@lot.Id"><img style="width: 100px; height: 100px" class="mb-3 mt-3 mr-3 ml-3" src="@("/images/" + (lot.Img ?? "noimage.png"))" alt="Картинка отсутствует"></a>
                        <a class="btn btn-light" style="font-size: 24px; font-weight: bold" asp-controller="Lot" asp-action="Edit" asp-route-id="@lot.Id">
                            <span>@lot.Name</span>
                        </a>
                    }
                    else
                    {
                        <a asp-controller="Lot" asp-action="LotPage" asp-route-id="@lot.Id"><img style="width: 100px; height: 100px" class="mb-3 mt-3 mr-3 ml-3" src="@("/images/" + (lot.Img ?? "noimage.png"))" alt="no image"></a>
                        <a class="btn btn-light" style="font-size: 24px; font-weight: bold" asp-controller="Lot" asp-action="LotPage" asp-route-id="@lot.Id">
                            <span>@lot.Name</span>
                        </a>
                    }
                    <span style="float: right; font-weight: bold; font-size: 24px" class="mr-3 ml-3 md-3 mt-3">$@lot.CurrentValue</span>
                    </div>
            </td>
            <td>
                <form asp-controller="Lot" asp-action="Delete" asp-route-id="@lot.Id" method="post">
                    <button type="submit" class="btn btn-sm btn-danger" onclick="return(confirm('Do you want to delete this lot?'));">
                        Delete
                    </button>
                </form>
            </td>
        </tr>
    }
</table>